### ISSUE TITLE
An error occurred while uninstalling Office-Addin: Error: ErrorInternalServerError

### ISSUE THREAD

**Issue by jthake** [knom/VSCode-Office-Manifest-Uploader#1]
I get an error when I try and upload the manifest. I'm using the Yeoman Generator and the name of the manifest is 

`manifest-testoutlookaddin.xml`

Log is

```
Opening file /Users/jeremythake/git/TestOutlookAddin/manifest-testoutlookaddin.xml
Successfully opened file /Users/jeremythake/git/TestOutlookAddin/manifest-testoutlookaddin.xml
Starting uninstalling Office-Addin to mail.office365.com as jthake@appdev365.onmicrosoft.com
Uninstalling application with id 7e8a4809-41fe-4ba7-b9cf-268eef391074
An error occurred while uninstalling Office-Addin: Error: ErrorInternalServerError
```

The add-in has not been ever installed before.

Is there any other places that there is a more granular verbose log?

**Comment by knom** [comment]
Ah.. This is because you're trying to uninstall an unexisting manifest..

The log messages could be clearer ...
