### ISSUE TITLE
No file name entered!

### ISSUE THREAD

**Issue by ruiqichen** [knom/VSCode-Office-Manifest-Uploader#3]
The input box flash alway quickly, and then console shows "No file name entered!" it happens very often, and i have to restart vscode to restore.

**Comment by knom** [comment]
Thanks for submitting the issue!
Which version of VSCode are you using on which OS platform?

Thx.

**Comment by Cyb3rP4w** [comment]
@knom I have the same issue VSCode 1.51.1 Mac OS X Big Sur 11.0.1
